url: "kanenstephens.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "kanen stephens" # the name of your site, e.g. ACME Corp.

author: "kanen stephens"
repo: "https://github.com/kanennn/kanenstephens"
